version: "2"

services:
  nginx:
    image: unixrepo.q.ru:5000/nginx:latest
    depends_on:
      - web
      - web2
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/uwsgi_params:/etc/nginx/uwsgi_params"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./app/static:/app/static:ro"
      - "./app/media:/app/media:ro"
    #  - "./build/app/charts_generator/media:/app/media:ro"
    network_mode: "host"
  web:
    image: unixrepo.q.ru:5200/q:latest
    user: 54297:54297
    volumes:
      - "./app/media:/app/media"
    network_mode: "host"
    expose:
      - "8383"
  web2:
    user: 54297:54297
    volumes:
      - "./app/media:/app/media"
    build:
      context: ./app2/
    network_mode: "host"
    expose:
      - "8484"
  runer:
    build:
      context: ./worker/
    environment:
      - START=0
      - END=63
    network_mode: "host"
  runer2:
    build:
      context: ./worker/
    environment:
      - START=64
      - END=127
    network_mode: "host"
  runer3:
    build:
      context: ./worker/
    environment:
      - START=128
      - END=191
    network_mode: "host"
  runer4:
    build:
      context: ./worker/
    environment:
      - START=192
      - END=255
    network_mode: "host"
