influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8087:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    - ./influxdb:/var/lib/influxdb

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3001:3000"
#  env_file:
#    - 'env.grafana'
  links:
    - influxdb
  volumes:
    - ./grafana:/var/lib/grafana