# Generated by Django 2.1.4 on 2018-12-08 17:03

from django.db import migrations, models
import django.db.models.deletion
import im.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата добавления', verbose_name='Create')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления', verbose_name='Update')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата удаления или пусто', null=True, verbose_name='Del')),
                ('name', models.CharField(help_text='Назание алгоритма, оригинальное', max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Алгоритм',
                'verbose_name_plural': '2. Алгоритмы',
            },
        ),
        migrations.CreateModel(
            name='AlgGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата добавления', verbose_name='Create')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления', verbose_name='Update')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата удаления или пусто', null=True, verbose_name='Del')),
                ('name', models.CharField(help_text='Назание группы алгоритмов, которые долдны работать последовательно', max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Группа алгоритмов',
                'verbose_name_plural': '3. Группы алгоритмов',
            },
        ),
        migrations.CreateModel(
            name='Im',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата добавления', verbose_name='Create')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления', verbose_name='Update')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Дата удаления или пусто', null=True, verbose_name='Del')),
                ('subs_id', models.CharField(blank=True, help_text='trace_id для отслеживания пути заявки', max_length=30, null=True, verbose_name='trace_id')),
                ('start_at', models.DateTimeField(blank=True, help_text='Дата когда заявка должна выполниться', null=True, verbose_name='Started')),
                ('debug_level', models.IntegerField(default=0, help_text='Писать ли расширенные логи по заявке', verbose_name='Debug')),
                ('trace_id', models.CharField(blank=True, help_text='trace_id для отслеживания пути заявки', max_length=30, null=True, verbose_name='trace_id')),
                ('prio', models.IntegerField(default=5, help_text='1 - высокий, 5 - низкий', verbose_name='Prio')),
                ('body', models.TextField(blank=True, help_text='Тело с параметрами', validators=[im.models.validate_json], verbose_name='body')),
                ('status', models.IntegerField(blank=True, help_text='Чат не будет обрабатываться в проме, если не NULL', null=True, verbose_name='Debug')),
                ('alg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im.Alg')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': '1. Заявки',
            },
        ),
        migrations.AlterUniqueTogether(
            name='alggroup',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='alg',
            name='alg_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im.AlgGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='alg',
            unique_together={('name',)},
        ),
    ]
