# Generated by Django 2.1.4 on 2018-12-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='im',
            name='status',
            field=models.IntegerField(blank=True, default=1, help_text='Чат не будет обрабатываться в проме, если не NULL', null=True, verbose_name='Debug'),
        ),
    ]
