# Generated by Django 2.1.3 on 2018-12-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0002_auto_20181208_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='im',
            name='alg',
        ),
    ]
