# Generated by Django 2.1.3 on 2018-12-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0003_remove_im_alg'),
    ]

    operations = [
        migrations.AddField(
            model_name='im',
            name='alg',
            field=models.CharField(default='old', max_length=30, verbose_name='Alg'),
        ),
    ]
