# Generated by Django 2.1.4 on 2018-12-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0004_im_alg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='im',
            name='subs_id',
            field=models.IntegerField(blank=True, help_text='trace_id для отслеживания пути заявки', max_length=30, null=True, verbose_name='trace_id'),
        ),
    ]
