# Generated by Django 2.1.4 on 2018-12-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0005_auto_20181209_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='im',
            name='q',
            field=models.IntegerField(default=None, help_text='Для партицирования'),
        ),
    ]
