# Generated by Django 2.1.4 on 2018-12-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0006_im_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='I',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='im',
            name='subs_id',
            field=models.IntegerField(blank=True, help_text='subs_id - ресурс', null=True, verbose_name='subs_id'),
        ),
    ]
